[package]
name = "dither"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive"] }
image = "0.24.0"
rand = { version = "0.8.5", features = ["small_rng"] }
